# Generated by Django 5.2.4 on 2025-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hoteluser_options_alter_hotelvender_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvender',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
