# Generated by Django 5.2.4 on 2025-07-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hotelbooking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelbooking',
            table='hotel_booking',
        ),
    ]
